SHELL := /bin/sh

.PHONY: test build smoke testnet-local

test:
	cd agent && env GOCACHE=$$PWD/.cache/go-build GOMODCACHE=$$PWD/.cache/go-mod go test ./...
	cd portal && env GOCACHE=$$PWD/.cache/go-build GOMODCACHE=$$PWD/.cache/go-mod go test ./...
	cd probe && env GOCACHE=$$PWD/.cache/go-build GOMODCACHE=$$PWD/.cache/go-mod go test ./...

build:
	cd agent && env GOCACHE=$$PWD/.cache/go-build GOMODCACHE=$$PWD/.cache/go-mod go build ./...
	cd portal && env GOCACHE=$$PWD/.cache/go-build GOMODCACHE=$$PWD/.cache/go-mod go build ./...
	cd probe && env GOCACHE=$$PWD/.cache/go-build GOMODCACHE=$$PWD/.cache/go-mod go build ./...

smoke:
	cd portal && env GOCACHE=$$PWD/.cache/go-build GOMODCACHE=$$PWD/.cache/go-mod go test ./internal/server -run TestSmokeE2E -count=1

testnet-local:
	cd portal && env GOCACHE=$$PWD/.cache/go-build GOMODCACHE=$$PWD/.cache/go-mod go test ./internal/server -run TestTestnetOperableE2E -count=1
